### ISSUE TITLE
Wow

### ISSUE THREAD

**Issue by fourcolors** [Gibby/docker-letsencrypt-dns-digitalocean#1]
I know this is for issues but just wanted to thank you for making this awesome container. It worked like a charm and saved me a LOT of time. 👍 

A simple container but probably one of my favorites. This really shows off how powerful docker is.

**Comment by Gibby** [comment]
@fourcolors you are welcome man. There wasn't anything out there for my configuration so I came up with this. I have the container running 24/7 and haven't had an issue yet.

**Comment by fourcolors** [comment]
@Gibby I think it makes sense. There are these sleeps for 300 that slow things down but I think that's because you need to wait for everything to be ok on the letsencrypt side of things?

**Comment by Gibby** [comment]
@fourcolors the sleep for 300 is in between the runs to create/renew the certs. That way it is not hammering away at their servers all the time.

**Comment by fourcolors** [comment]
@Gibby Oh, i just realized I'm suppose to leave this running in the background yeah? I was under the impression I managed when this script ran.

**Comment by Gibby** [comment]
@fourcolors yeah, just leave running, restart if you update domain list

**Comment by fourcolors** [comment]
@Gibby Ok I guess I'm still learning how this works. SSL kind of confuses me sometimes. 

So this just keeps my cert up to date but this doesn't set up the domain on my digital ocean instance correct? that has to be manually configured?

**Comment by Gibby** [comment]
@fourcolors correct, that part could probably be automated too. All this does is use the DNS service offered by digital ocean and creates the certs through lets encrypt.
